"""updated Message Model

Revision ID: 1e93786bf0d6
Revises: d255a6e53c8e
Create Date: 2024-05-27 14:43:26.451094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e93786bf0d6'
down_revision = 'd255a6e53c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=True))
        batch_op.drop_column('credits')
        batch_op.drop_column('plan')
        batch_op.drop_column('active')
        batch_op.drop_column('email')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
